version: '3'

services:

  proxy:
    build: ./
    depends_on:
      - 'checkout'
      - 'carousel'
    ports:
      - '3000:3000'

  carousel:
    image: pgrover5/airbnb_carousel
    depends_on:
      - 'database'
    ports: 
      - '2500:2500'
  
  # checkout:
  #   image: dapaul2121/airbnb_proxy:checkout
  #   depends_on:
  #     - 'database'
  #   ports: 
  #     - '2000:2000'    

  database:
    image: mongo:latest
